spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pssc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #????????
      min-idle: 10 #???????
      max-active: 20 #?????
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #?????????
      stat-view-servlet: #???????????????
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis?????
    database: 0 # Redis?????????0?
    port: 6379 # Redis???????
    password: # Redis?????????????
    timeout: 300ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    jwt:
      key: sahfui1437545154;kdiofjadf
      expire: 7
  mail:
    host: smtp.163.com
    username: 15280260130@163.com
    password: SVUINWZBORXRTLNC
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8080


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.putianhouduan.PhotovoltaicSmartSupplyChain.entity

# 修改swagger的路径匹配配置，使其兼容新版的SpringBoot
