spring:
  application:
   name: my-project-backend
  security:
    jwt:
      key: sahfui1437545154;kdiofjadf
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/text