spring:
  mail:
    host: smtp.163.com
    username: 15280260130@163.com
    password: SVUINWZBORXRTLNC
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  application:
   name: my-project-backend
  security:
    jwt:
      key: sahfui1437545154;kdiofjadf
      expire: 7
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/text
  amqp:
    deserialization:
      trust:
        all:
          true
